--
-- PostgreSQL database dump
--

-- Dumped from database version 12.5 (Debian 12.5-1.pgdg100+1)
-- Dumped by pg_dump version 12.2

-- Started on 2020-12-16 13:50:41

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 7 (class 2615 OID 41008)
-- Name: public; Type: SCHEMA; Schema: -; Owner: admin
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO admin;

--
-- TOC entry 2925 (class 0 OID 0)
-- Dependencies: 7
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: admin
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 202 (class 1259 OID 41009)
-- Name: ingredient; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.ingredient (
    ingredientid integer NOT NULL,
    ingredientname character varying,
    quantity character varying
);


ALTER TABLE public.ingredient OWNER TO admin;

--
-- TOC entry 203 (class 1259 OID 41015)
-- Name: ingredient_ingredientid_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.ingredient ALTER COLUMN ingredientid ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.ingredient_ingredientid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 204 (class 1259 OID 41017)
-- Name: recipe; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.recipe (
    recipename character varying,
    recipeid integer NOT NULL,
    categoryname character varying,
    picture character varying,
    rating integer DEFAULT 0,
    cheffname character varying,
    preparation character varying,
    ingredients json
);


ALTER TABLE public.recipe OWNER TO admin;

--
-- TOC entry 205 (class 1259 OID 41024)
-- Name: recipe_recipeid_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.recipe ALTER COLUMN recipeid ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.recipe_recipeid_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 2916 (class 0 OID 41009)
-- Dependencies: 202
-- Data for Name: ingredient; Type: TABLE DATA; Schema: public; Owner: admin
--



--
-- TOC entry 2918 (class 0 OID 41017)
-- Dependencies: 204
-- Data for Name: recipe; Type: TABLE DATA; Schema: public; Owner: admin
--

INSERT INTO public.recipe VALUES ('Caserola', 4, 'Pasta', 'http://lorempixel.com/200/300/food/5', 4, 'Alta Winters', 'Minim eiusmod aute esse amet. Voluptate Lorem duis nostrud anim ex cupidatat. Consectetur laborum et Lorem id ad elit excepteur quis do fugiat incididunt dolor aliqua laborum. Quis pariatur pariatur irure eiusmod exercitation laboris sint consectetur reprehenderit tempor consequat esse minim officia. Elit aliquip eiusmod veniam velit nisi. Dolore magna adipisicing enim nulla occaecat proident.', '[ { "name":"Apples", "quantity":"7" }, { "name":"Milk", "quantity":"500 liters" }, { "name":"Oil", "quantity":"100l" } ] ');
INSERT INTO public.recipe VALUES ('Filled Tomato', 0, 'Dessert', 'http://lorempixel.com/200/300/food/1', 5, 'Smith Tanner', 'Tempor id laborum ut dolore aliquip consectetur elit mollit esse ullamco. Sit culpa ipsum incididunt id cupidatat laboris irure aute occaecat id. Adipisicing in ea elit eiusmod ex in. Culpa deserunt enim eiusmod minim anim eiusmod amet laboris sit. Ad magna laboris eiusmod cupidatat laborum veniam velit ea exercitation deserunt dolor incididunt.', '[ { "name":"Pork Meat", "quantity":"1k" }, { "name":"Salt", "quantity":"50g" }, { "name":"Pepper", "quantity":"100g" } ] ');
INSERT INTO public.recipe VALUES ('Rib Eye', 1, 'Meat', 'http://lorempixel.com/200/300/food/2', 3, 'Shanna Hicks', 'Commodo consequat in elit ut laborum adipisicing adipisicing in cillum incididunt exercitation tempor laboris veniam. Dolore veniam cillum laborum qui. Elit consectetur tempor qui sit id nisi et ex est cupidatat. Elit elit voluptate fugiat eu incididunt.', '[ { "name":"Tomato", "quantity":"1k" }, { "name":"Potatoe", "quantity":"1/2k" }, { "name":"Pineapple", "quantity":"2" } ] ');
INSERT INTO public.recipe VALUES ('Rib Eye', 2, 'Dessert', 'http://lorempixel.com/200/300/food/3', 3, 'Silva Fields', 'Aliqua consequat non ipsum laboris sunt ad quis sunt sit deserunt. Nostrud deserunt velit proident sint non quis incididunt elit voluptate dolor dolor esse sunt id. Laboris fugiat sit esse reprehenderit ullamco commodo laborum aliquip. Est dolore et mollit consectetur non ipsum nisi nostrud est laborum laborum ipsum esse. Dolor sint ea ipsum pariatur laborum ullamco ea aute sint. Exercitation nostrud ut veniam dolore eiusmod irure mollit pariatur aute excepteur. Voluptate quis mollit Lorem mollit sunt adipisicing.', '[ { "name":"Water", "quantity":"1 liter" }, { "name":"Ice", "quantity":"2 pieces" }, { "name":"Sugar", "quantity":"50g" } ] ');
INSERT INTO public.recipe VALUES ('Caserola', 5, 'Meat', 'http://lorempixel.com/200/300/food/6', 4, 'Saunders Briggs', 'Reprehenderit aliquip ullamco minim esse velit minim cillum id consectetur. Aute aute reprehenderit dolor enim ad qui ad minim magna aliqua. Commodo veniam elit nisi fugiat sint reprehenderit. Proident veniam eu nulla occaecat aliqua irure fugiat eiusmod excepteur qui.', '[ { "name":"Canned Corn", "quantity":"1 cans" }, { "name":"Pickles", "quantity":"1k" }, { "name":"Hot Sauce", "quantity":"1 tbsp" } ] ');
INSERT INTO public.recipe VALUES ('Cesar Salad', 9, 'Salad', 'http://placehold.it/200x300', 1, 'Lottie Quinn', 'Eu ad aliquip consequat eiusmod tempor. Irure ullamco in irure sint consectetur magna commodo dolor magna anim ullamco enim officia. Nulla voluptate ipsum exercitation nisi culpa ex minim deserunt laboris. Irure enim ullamco non irure aute laborum quis ex velit proident. Velit eu sint sint nostrud do exercitation.', '[ { "name":"Rice", "quantity":"5 pounds" }, { "name":"Beans", "quantity":"3 pounds" }, { "name":"Fish", "quantity":"100g" } ] ');
INSERT INTO public.recipe VALUES ('Cesar Salad', 7, 'Pasta', 'http://lorempixel.com/200/300/food/8', 2, 'Sadie Dillard', 'Consectetur consectetur eiusmod eiusmod dolore incididunt proident ex magna nostrud aute reprehenderit Lorem dolor. Qui laboris ullamco proident in excepteur deserunt veniam cillum. Consectetur reprehenderit veniam deserunt et sint adipisicing voluptate aliqua nulla duis minim nisi aute. Officia aliqua consequat ea proident ex consequat incididunt ea. Cillum ut duis irure sunt. Commodo eu incididunt aliqua cupidatat deserunt.', '[ { "name":"Hot Sauce", "quantity":"1 tbsp" }, { "name":"Banana", "quantity":"5" }, { "name":"Water", "quantity":"500 liters" }, { "name":"Flour", "quantity":"100g" } ] ');
INSERT INTO public.recipe VALUES ('Rice and Beans', 8, 'Pasta', 'http://lorempixel.com/200/300/food/9', 2, 'Vinson Buchanan', 'Irure laborum eiusmod amet laboris commodo id ea occaecat adipisicing incididunt ipsum. Aute irure sunt eu duis esse mollit irure anim ad exercitation aliquip labore deserunt excepteur. Elit labore consectetur quis deserunt anim tempor laboris duis est. Consequat minim pariatur qui minim laboris ad elit veniam pariatur eu. Reprehenderit occaecat anim et aute id officia sunt aliqua. Aliquip fugiat aliqua laboris magna nulla anim quis nisi enim.', '[ { "name":"Rice", "quantity":"5 pounds" }, { "name":"Beans", "quantity":"3 pounds" }, { "name":"Meat", "quantity":"100g" } ] ');
INSERT INTO public.recipe VALUES ('Cofee Late', 6, 'Salad', 'http://lorempixel.com/200/300/food/7', 4, 'Stephens Whitfield', 'Adipisicing non minim pariatur cillum. Consectetur ullamco deserunt aliqua magna qui qui fugiat incididunt dolore id consequat deserunt sit. Culpa magna ut voluptate nulla labore occaecat minim. Veniam sunt cillum sint pariatur irure cupidatat irure sint occaecat et velit. Aute aliqua sit est sint.', '[ { "name":"Hot Sauce", "quantity":"1 tbsp" } ] ');
INSERT INTO public.recipe VALUES ('Carbonara', 3, 'Salad', 'http://lorempixel.com/200/300/food/4', 1, 'Harmon Powell', 'Excepteur amet esse irure magna quis labore sint. Commodo ullamco duis excepteur tempor sint dolore excepteur proident et sunt velit. Duis deserunt ea laboris elit ad quis dolore labore sit eu. Excepteur proident elit irure velit do Lorem exercitation. Ea voluptate aliqua elit reprehenderit. Velit aliqua do eu exercitation enim. Proident duis sunt adipisicing pariatur cillum officia id officia veniam do in.', '[ { "name":"Banana", "quantity":"5" }, { "name":"Water", "quantity":"500 liters" }, { "name":"Flour", "quantity":"100g" } ] ');
INSERT INTO public.recipe VALUES ('TEST', 32, 'All Recipes', NULL, 0, 'TEST', 'TEST', '[]');
INSERT INTO public.recipe VALUES ('Tamal', 34, 'Salad', NULL, 0, 'Carlos', 'Cocinar todo.', '[{"name":"Masa","quantity":"1k"}]');


--
-- TOC entry 2926 (class 0 OID 0)
-- Dependencies: 203
-- Name: ingredient_ingredientid_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.ingredient_ingredientid_seq', 1, false);


--
-- TOC entry 2927 (class 0 OID 0)
-- Dependencies: 205
-- Name: recipe_recipeid_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.recipe_recipeid_seq', 34, true);


--
-- TOC entry 2787 (class 2606 OID 41027)
-- Name: ingredient ingredient_pk; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.ingredient
    ADD CONSTRAINT ingredient_pk PRIMARY KEY (ingredientid);


--
-- TOC entry 2789 (class 2606 OID 41029)
-- Name: recipe recipe_pk; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.recipe
    ADD CONSTRAINT recipe_pk PRIMARY KEY (recipeid);


-- Completed on 2020-12-16 13:50:42

--
-- PostgreSQL database dump complete
--

